name: 构建和部署

on:
  # 当代码被推送到仓库时触发
  # push:
  #   branches:
  #     - main  # 可以根据需要更改为你的目标分支
  workflow_dispatch:
    inputs:
      build:
        description: "是否构建"
        required: true
        default: "true"
      deploy:
        description: "是否部署"
        required: true
        default: "true"

jobs:
  # 构建环境
  build_env:
    runs-on: ubuntu-latest
    steps:
      - name: 验证阿里云登录
        run: |
          sudo docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }}  ${{ secrets.ALIYUN_REGISTRY }}

  # 构建和推送 Docker 镜像
  build:
    # 在哪个环境下运行
    runs-on: ubuntu-latest
    needs: build_env
    if: github.event.inputs.build == 'true'
    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 安装 Docker 构建工具
      uses: docker/setup-buildx-action@v2

    - name: 登录到阿里云 Docker 镜像仓库
      uses: docker/login-action@v2
      with:
        username: ${{secrets.ALIYUN_REGISTRY_USER}}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        registry: ${{ secrets.ALIYUN_REGISTRY }}

    - name: 构建并推送 Docker 镜像
      run: |
        docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest ./src
        docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'true'
    needs: build
    environment:
      name: production
      url: https://demo.faceman.cn
      
    steps:
    - name: SSH 连接到服务器并部署应用
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.ALIYUN_SERVER_IP }}
        username: ${{ secrets.ALIYUN_SERVER_USER }}
        password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
        port: ${{ secrets.ALIYUN_SERVER_PORT }}
        # key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../../docker/demo
          sudo docker pull ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest
          sudo docker compose down || true
          sudo docker compose up -d