name: Build

on:
  # 当代码被推送到仓库时触发
  # push:
  #   branches:
  #     - main  # 可以根据需要更改为你的目标分支
  workflow_dispatch:
    inputs:
      run_build_env:
        description: "Run build_env true or false"
        required: true
        default: "true"
      build:
        description: "Run build true or false"
        required: true
        default: "true"
jobs:
  # 构建环境
  build_env:
    runs-on: ubuntu-latest
    steps:
      - name: check login aliyun  验证阿里云登录
        run: |
          sudo docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }}  ${{ secrets.ALIYUN_REGISTRY }}

  # 构建和推送 Docker 镜像
  build:
    # 在哪个环境下运行
    runs-on: ubuntu-latest
    needs: build_env
    if: github.event.inputs.run_build_env == 'true'
    steps:
      # 检查代码
    - name: Checkout code
      uses: actions/checkout@v2

      # 安装 Docker 构建工具
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # 登录到阿里云 Docker 镜像仓库
    - name: Log in to Alibaba Cloud Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.ALIYUN_REGISTRY_USER}}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        registry: ${{ secrets.ALIYUN_REGISTRY }}

      # 构建并推送 Docker 镜像
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest ./src
        docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest