name: Deploy

on:
  # 当代码被推送到仓库时触发
  # push:
  #   branches:
  #     - main  # 可以根据需要更改为你的目标分支
  workflow_dispatch:
    inputs:
      deploy:
        description: "Run deploy true or false"
        required: true
        default: "true"

jobs:
  deploy:
    runs-on: self-hosted
    if: github.event.inputs.deploy == 'true'
    environment:
      name: production
      url: https://demo.faceman.cn
      
    steps:
      # 检查代码
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run deploy
      run: |
        cd docker
        # 拉取最新镜像
        docker pull ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest
        # 检查服务是否存在
          if  docker-compose -p demo ps > /dev/null 2>&1; then
              # 服务存在，停止并删除
              docker compose -f docker-compose.yml -p demo down
              echo "compose demo removed."
              sleep 10
          fi
        sudo docker compose -f docker-compose.yml -p demo pull && docker compose -f docker-compose.yml -p demo up -d