name: Build and Deploy

on:
  # 当代码被推送到仓库时触发
  # push:
  #   branches:
  #     - main  # 可以根据需要更改为你的目标分支
  workflow_dispatch:
    inputs:
      run_build_env:
        description: "Run build_env true or false"
        required: true
        default: "true"
      build:
        description: "Run build true or false"
        required: true
        default: "true"
      deploy:
        description: "Run deploy true or false"
        required: true
        default: "false"

jobs:
  # 构建环境
  build_env:
    runs-on: ubuntu-latest
    steps:
      - name: check login aliyun  验证阿里云登录
        run: |
          sudo docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }}  ${{ secrets.ALIYUN_REGISTRY }}

  # 构建和推送 Docker 镜像
  build:
    # 在哪个环境下运行
    runs-on: ubuntu-latest
    if: github.event.inputs.run_build_env == 'true'
    steps:
      # 检查代码
    - name: Checkout code
      uses: actions/checkout@v2

      # 安装 Docker 构建工具
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # 登录到阿里云 Docker 镜像仓库
    - name: Log in to Alibaba Cloud Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.ALIYUN_REGISTRY_USER}}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        registry: ${{ secrets.ALIYUN_REGISTRY }}

      # 构建并推送 Docker 镜像
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest ./src
        docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'true'
    needs: build
    environment:
      name: production
      url: https://demo.faceman.cn
      
    steps:
      # 检查代码
    - name: Checkout code
      uses: actions/checkout@v2
      # SSH 连接到服务器并部署应用
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.ALIYUN_SERVER_IP }}
        username: ${{ secrets.ALIYUN_SERVER_USER }}
        # password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
        port: ${{ secrets.ALIYUN_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../docker/demo
          docker pull ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest
          docker compose down || true
          docker compose up -d