name: Build and Manual Deploy

on:
  push:
    branches:
      - main  # 可以根据需要更改为你的目标分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ deploy.DOCKER_USERNAME }}
        password: ${{ deploy.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t webtest:latest ./src
        docker tag webtest:latest ${{ deploy.DOCKER_USERNAME }}/webtest:latest
        docker push ${{ deploy.DOCKER_USERNAME }}/webtest:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://your-production-url.com
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ deploy.ALIYUN_SERVER_IP }}
        username: ${{ deploy.ALIYUN_SERVER_USER }}
        key: ${{ deploy.SSH_PRIVATE_KEY }}
        port: ${{ deploy.ALIYUN_SERVER_PORT }}
        script: |
          docker pull ${{ deploy.DOCKER_USERNAME }}/webtest:latest
          docker stop webtest || true
          docker rm webtest || true
          docker run -d --name webtest -p 80:80 ${{ deploy.DOCKER_USERNAME }}/webtest:latest