name: Build and Manual Deploy

on:
  push:
    branches:
      - main  # 可以根据需要更改为你的目标分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Alibaba Cloud Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{secrets.ALIYUN_REGISTRY_USER}}
        password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
        registry: ${{ secrets.ALIYUN_REGISTRY }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest ./src
        docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: https://demo.faceman.cn
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.ALIYUN_SERVER_IP }}
        username: ${{ secrets.ALIYUN_SERVER_USER }}
        # password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
        port: ${{ secrets.ALIYUN_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest
          docker stop ${{ secrets.IMAGE_NAME }} || true
          docker rm ${{ secrets.IMAGE_NAME }} || true
          docker run -d --name ${{ secrets.IMAGE_NAME }} -p 7121:80 ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest