name: Deploy

on:
  # 当代码被推送到仓库时触发
  # push:
  #   branches:
  #     - main  # 可以根据需要更改为你的目标分支
  workflow_dispatch:
    inputs:
      deploy:
        description: "Run deploy true or false"
        required: true
        default: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'true'
    environment:
      name: production
      url: https://demo.faceman.cn
      
    steps:
      # 检查代码
    - name: Checkout code
      uses: actions/checkout@v2
      # SSH 连接到服务器并部署应用
    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.ALIYUN_SERVER_IP }}
        username: ${{ secrets.ALIYUN_SERVER_USER }}
        # password: ${{ secrets.ALIYUN_SERVER_PASSWORD }}
        port: ${{ secrets.ALIYUN_SERVER_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ../docker/demo
          docker pull ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/${{ secrets.IMAGE_NAME }}:latest
          docker compose down || true
          docker compose up -d